CREATE TABLE IF NOT EXISTS Order_Dish (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL,
  dish_id INTEGER NOT NULL,
  quantity INT NOT NULL,
  FOREIGN KEY (order_id) REFERENCES "Order"(id) ON DELETE CASCADE,
  FOREIGN KEY (dish_id) REFERENCES Dish(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
);