CREATE TABLE IF NOT EXISTS Tables (
  id SERIAL PRIMARY KEY,
  number INT NOT NULL,
  seats INT NOT NULL,
  occupied BOOLEAN NOT NULL DEFAULT FALSE,
  restaurant_id UUID NOT NULL,
  FOREIGN KEY (restaurant_id) REFERENCES Restaurant(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)